### ISSUE TITLE
Text not wrapped on spell interface

### ISSUE THREAD

**Issue by Ignaramico** [KorGgenT/Cataclysm-DDA#81] opened 2019-09-22 16:07 UTC
# Describe the bug
The text in the spell interface doesnt show correctly

# Steps To Reproduce

1. learn a spell from the arcana mod
2. open spell interface
3. check the spell information panel

# Screenshots
![Screenshot_1](https://user-images.githubusercontent.com/34730575/65390884-2f175780-dd28-11e9-8bef-b0fb859f37bc.jpg)

# Additional context
After testing, the issue comes from the spells learned via the mutation of the arcana mod (the dragon and paragon categories) the ones learned via the scroll and the ones from magiclysm mod doesnt cause the problem, but if you learn the spells via those mutation categories mentioned, the interface text gets messed for the rest of the spells/playthrough.
I put it in your mod issue section since is your main work.

**Comment by Ignaramico** [comment] 2019-09-22 16:12
@chavolt

**Comment by Ignaramico** [comment] 2019-09-22 16:12
@chaosvolt

**Comment by chaosvolt** [comment] 2019-09-22 16:25
Shit, guessing that's due to name length. I'll have to see if I can implement that text color idea Korg suggested a while back instead?

**Comment by KorGgenT** [comment] 2019-09-22 17:06
yeah the obvious solution is strictly limiting the character length displayed on the spellcasting menu. this will have repercussions for those very wordy spell names.

**Comment by chaosvolt** [comment] 2019-09-22 17:38
Yeah. I can puzzle out how to reword them, and I'll want to test out text color so that the player can tell arcane blessings from magic signs and such at a glance.

What was the format for that again? I'm trying to find an example of it used in the JSON itself in the meantime...

**Comment by chaosvolt** [comment] 2019-09-22 18:24
Okay, so...I've removed the name-based method for distinguishing spell types in favor of text color, and updated my test build just in case.

![image](https://user-images.githubusercontent.com/11582235/65392611-4a8c5d80-dd3c-11e9-945f-1edd026cbdee.png)

I'm highlighting what it now the longest spell name in Arcana, and it is very clearly nowhere near the edge of the second box. The UI seems to be squashing the second box no matter what.

**Comment by chaosvolt** [comment] 2019-09-22 18:27
Okay, woah what. I did a test in vanilla and it didn't do that:
![image](https://user-images.githubusercontent.com/11582235/65392655-ab1b9a80-dd3c-11e9-80f0-c34be1fa96ea.png)

I can only guess that the cause might be that the <color> tags in the spell names are somehow being parsed for the sake of spacing?

**Comment by KorGgenT** [comment] 2019-09-22 18:36
the tags are fairly likely being parsed in some fashion. this however has to do with the uilist implementation, which i do not have an intention of changing any time soon

**Comment by chaosvolt** [comment] 2019-09-22 18:38
Hmm. That axes the idea of using text color then...wrangling the character limits to make spell names a sane length is looking to be more and more hassle by the minute. I can at least shorten the prefixes a bit, but it's still going to be lengthy just to allow reasonably differentiating between the types of spell. Not sure what the best fix here is. ._.

**Comment by KorGgenT** [comment] 2019-09-22 18:39
just give them a class named by the prefix or something.

**Comment by chaosvolt** [comment] 2019-09-22 18:41
Ah, that could work, though that will add to the trait list, plus some of the spells use spell class to sanity-check the mutation-dependent stuff they have to use.

**Comment by KorGgenT** [comment] 2019-09-22 18:42
you could also put it in the description.

**Comment by chaosvolt** [comment] 2019-09-22 18:42
That'd work too, yeah. I'll work on it for now. Thank you, in any case.

**Comment by chaosvolt** [comment] 2019-09-22 20:45
Should now be fixed by https://github.com/chaosvolt/cdda-arcana-mod/commit/84773b85d8b9ae59aff4174f7b6ff67eebac3a93, tell me if anything else comes up.

**Closed** 2019-09-22 21:50 UTC
